"""
Reasoning Layer — Gemini-powered explanation generation.

Per PRD §10.3:
- Given the processed summary (§6) and question, returns structured JSON:
  {summary, insights, confidence_signal, chart_type}
- No chart_data in LLM output — that's generated by Pandas
- Temperature 0.4–0.5
"""
import httpx
import json
from app.core.config import get_settings
from typing import Optional

GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"

REASONING_SYSTEM_PROMPT = """You are a business data analyst explaining query results to a non-technical business owner.

Given the question and processed data summary, provide:
1. A plain-language summary (2-4 sentences) explaining what the data shows
2. Key insights as bullet points (2-5 insights)
3. Your confidence signal (high/medium/low)
4. A chart type recommendation

OUTPUT FORMAT: Return ONLY a JSON object, no markdown, no explanation:
{
  "summary": "Plain-language 2-4 sentence explanation",
  "insights": ["Insight 1", "Insight 2", "Insight 3"],
  "confidence_signal": "high | medium | low",
  "chart_type": "line | bar | pie | scatter | stat | none"
}

RULES:
- Be concise and clear — the reader is a business owner, not a data engineer
- Never fabricate numbers not present in the data
- If the result is empty or unclear, say so honestly
- CURRENCY AND NUMBER FORMATTING:
  - The business operates in Bangladesh and its currency is Bangladeshi Taka (BDT / ৳ / Taka).
  - NEVER use the dollar sign ($) or USD.
  - Express all monetary amounts using '৳' or 'BDT' or 'Taka' (e.g. ৳80 or BDT 80, ৳70, ৳10).
- Chart type should match the data shape:
  - Time series data -> "line"
  - Category comparison -> "bar"
  - Part-to-whole -> "pie"
  - Two numeric variables -> "scatter"
  - Single number -> "stat"
  - Doesn't fit -> "none"
- Keep the summary conversational but grounded in the data"""


async def generate_reasoning(
    question: str,
    summary: dict,
    chart_type_from_pandas: str = "none",
    conversation_context: Optional[str] = None,
    locale: str = "en-BD",
) -> dict:
    """
    Generate a structured explanation from the processed summary.

    Returns: {summary, insights, confidence_signal, chart_type}
    """
    settings = get_settings()

    is_bangla = locale.lower().startswith("bn")
    response_language = (
        "Bangla (Bengali). Write the summary and every insight entirely in natural Bangla; "
        "keep only product names, SKUs, and unavoidable technical identifiers unchanged."
        if is_bangla else
        "English. Write the summary and every insight in clear English."
    )
    prompt_parts = [
        REASONING_SYSTEM_PROMPT,
        f"\nRESPONSE LANGUAGE (MANDATORY): {response_language}",
    ]

    if conversation_context:
        prompt_parts.append(f"\nConversation context:\n{conversation_context}")

    prompt_parts.append(f"\nUser question: {question}")
    prompt_parts.append(f"\nData summary:\n{json.dumps(summary, indent=2, default=str)}")
    prompt_parts.append(f"\nDeterministic chart type from data analysis: {chart_type_from_pandas}")
    prompt_parts.append("\nReturn your JSON response:")

    full_prompt = "\n".join(prompt_parts)

    async with httpx.AsyncClient(timeout=30.0) as client:
        try:
            response = await client.post(
                GEMINI_API_URL,
                params={"key": settings.gemini_api_key},
                json={
                    "contents": [{"parts": [{"text": full_prompt}]}],
                    "generationConfig": {
                        "temperature": 0.45,
                        "maxOutputTokens": 1024,
                        "topP": 0.9,
                    },
                },
            )

            if response.status_code != 200:
                # Fallback: return basic explanation without LLM
                return _fallback_reasoning(question, summary, chart_type_from_pandas, locale)

            data = response.json()
            candidates = data.get("candidates", [])
            if not candidates:
                return _fallback_reasoning(question, summary, chart_type_from_pandas, locale)

            text = candidates[0]["content"]["parts"][0]["text"].strip()

            # Clean up markdown code blocks
            if text.startswith("```"):
                lines = text.split("\n")
                text = "\n".join(lines[1:-1]).strip()

            # Parse JSON response
            result = json.loads(text)

            # Override chart_type with the Pandas-generated one if available
            # (PRD §5.5: Gemini only recommends type, Pandas determines actual chart data)
            if chart_type_from_pandas != "none":
                result["chart_type"] = chart_type_from_pandas

            return result

        except (json.JSONDecodeError, KeyError, IndexError):
            return _fallback_reasoning(question, summary, chart_type_from_pandas, locale)
        except Exception:
            return _fallback_reasoning(question, summary, chart_type_from_pandas, locale)


def _fallback_reasoning(
    question: str, summary: dict, chart_type: str, locale: str = "en-BD"
) -> dict:
    """Fallback reasoning when LLM is unavailable."""
    row_count = summary.get("rows", 0)

    is_bangla = locale.lower().startswith("bn")
    if row_count == 0:
        return {
            "summary": (
                "আপনার প্রশ্নের সঙ্গে মেলে এমন কোনো তথ্য পাওয়া যায়নি।"
                if is_bangla else
                "The query returned no results. There may be no data matching your question."
            ),
            "insights": [
                "প্রশ্নের শর্ত অনুযায়ী কোনো তথ্য পাওয়া যায়নি"
                if is_bangla else "No data found matching the query criteria"
            ],
            "confidence_signal": "low",
            "chart_type": "none",
        }

    # Build basic summary from stats
    numeric_stats = summary.get("numeric_stats", {})
    insights = []
    for col, stats in numeric_stats.items():
        if stats.get("sum") is not None:
            insights.append(
                f"মোট {col}: ৳{stats['sum']:,.2f}"
                if is_bangla else f"Total {col}: ৳{stats['sum']:,.2f}"
            )
        if stats.get("mean") is not None:
            insights.append(
                f"গড় {col}: ৳{stats['mean']:,.2f}"
                if is_bangla else f"Average {col}: ৳{stats['mean']:,.2f}"
            )

    return {
        "summary": (
            f"আপনার প্রশ্নের ভিত্তিতে {row_count}টি ফলাফল পাওয়া গেছে। বিস্তারিত নিচের তথ্যে দেখুন।"
            if is_bangla else
            f"The query returned {row_count} rows. See the data below for details."
        ),
        "insights": insights[:5] if insights else [
            f"{row_count}টি রেকর্ড পাওয়া গেছে"
            if is_bangla else f"Found {row_count} records"
        ],
        "confidence_signal": "medium",
        "chart_type": chart_type,
    }
